# Generated by Django 6.0.7 on 2026-07-28 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=120, unique=True)),
                ('config', models.JSONField(help_text='CampaignConfig as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('research', 'research'), ('enrich', 'enrich'), ('consolidate', 'consolidate'), ('outreach', 'outreach')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('done', 'done'), ('error', 'error')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('result_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
