# Generated by Django 6.0.7 on 2026-07-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
