# Generated by Django 6.0.7 on 2026-07-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_run_processed_run_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('done', 'done'), ('error', 'error'), ('canceled', 'canceled')], default='pending', max_length=20),
        ),
    ]
