# Generated by Django 6.0.7 on 2026-07-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('done', 'done'), ('error', 'error'), ('canceled', 'canceled'), ('paused', 'paused')], default='pending', max_length=20),
        ),
    ]
