# Generated by Django 6.0.7 on 2026-07-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_run_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
