# Generated by Django 6.0.7 on 2026-08-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_campaign_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('type', models.CharField(choices=[('lara', 'lara'), ('azure_openai', 'azure_openai'), ('azure_foundry', 'azure_foundry'), ('manual', 'manual')], max_length=20)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('web_search', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('is_default_research', models.BooleanField(default=False)),
                ('api_key_env', models.CharField(blank=True, default='', max_length=80)),
                ('endpoint_env', models.CharField(blank=True, default='', max_length=80)),
                ('assistant_id_env', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default_research', 'name'],
            },
        ),
    ]
