# Generated by Django 6.0.7 on 2026-08-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_seed_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersetting',
            name='endpoint_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
