"""World country-code normalization (ISO 3166-1).

Provided lists sometimes carry ISO codes (``DE``, ``ESP``) in the country column
instead of full names. Codes don't match the language / Apollo-geo lookups in
``schema.py`` (which key off full names like ``Germany``), so outreach falls back
to English and Apollo geo filtering degrades. ``normalize_country`` expands a
2- or 3-letter code to its canonical English short name; anything that isn't a
recognized code is returned unchanged.
"""

from __future__ import annotations

# (alpha-2, alpha-3, canonical English short name) for every ISO 3166-1 country.
# Short names are chosen to match the language / Apollo-geo maps in schema.py.
_ISO_3166: tuple[tuple[str, str, str], ...] = (
    ("AF", "AFG", "Afghanistan"),
    ("AX", "ALA", "Åland Islands"),
    ("AL", "ALB", "Albania"),
    ("DZ", "DZA", "Algeria"),
    ("AS", "ASM", "American Samoa"),
    ("AD", "AND", "Andorra"),
    ("AO", "AGO", "Angola"),
    ("AI", "AIA", "Anguilla"),
    ("AQ", "ATA", "Antarctica"),
    ("AG", "ATG", "Antigua and Barbuda"),
    ("AR", "ARG", "Argentina"),
    ("AM", "ARM", "Armenia"),
    ("AW", "ABW", "Aruba"),
    ("AU", "AUS", "Australia"),
    ("AT", "AUT", "Austria"),
    ("AZ", "AZE", "Azerbaijan"),
    ("BS", "BHS", "Bahamas"),
    ("BH", "BHR", "Bahrain"),
    ("BD", "BGD", "Bangladesh"),
    ("BB", "BRB", "Barbados"),
    ("BY", "BLR", "Belarus"),
    ("BE", "BEL", "Belgium"),
    ("BZ", "BLZ", "Belize"),
    ("BJ", "BEN", "Benin"),
    ("BM", "BMU", "Bermuda"),
    ("BT", "BTN", "Bhutan"),
    ("BO", "BOL", "Bolivia"),
    ("BQ", "BES", "Bonaire, Sint Eustatius and Saba"),
    ("BA", "BIH", "Bosnia and Herzegovina"),
    ("BW", "BWA", "Botswana"),
    ("BV", "BVT", "Bouvet Island"),
    ("BR", "BRA", "Brazil"),
    ("IO", "IOT", "British Indian Ocean Territory"),
    ("BN", "BRN", "Brunei"),
    ("BG", "BGR", "Bulgaria"),
    ("BF", "BFA", "Burkina Faso"),
    ("BI", "BDI", "Burundi"),
    ("CV", "CPV", "Cape Verde"),
    ("KH", "KHM", "Cambodia"),
    ("CM", "CMR", "Cameroon"),
    ("CA", "CAN", "Canada"),
    ("KY", "CYM", "Cayman Islands"),
    ("CF", "CAF", "Central African Republic"),
    ("TD", "TCD", "Chad"),
    ("CL", "CHL", "Chile"),
    ("CN", "CHN", "China"),
    ("CX", "CXR", "Christmas Island"),
    ("CC", "CCK", "Cocos (Keeling) Islands"),
    ("CO", "COL", "Colombia"),
    ("KM", "COM", "Comoros"),
    ("CG", "COG", "Congo"),
    ("CD", "COD", "Congo (Democratic Republic)"),
    ("CK", "COK", "Cook Islands"),
    ("CR", "CRI", "Costa Rica"),
    ("CI", "CIV", "Côte d'Ivoire"),
    ("HR", "HRV", "Croatia"),
    ("CU", "CUB", "Cuba"),
    ("CW", "CUW", "Curaçao"),
    ("CY", "CYP", "Cyprus"),
    ("CZ", "CZE", "Czech Republic"),
    ("DK", "DNK", "Denmark"),
    ("DJ", "DJI", "Djibouti"),
    ("DM", "DMA", "Dominica"),
    ("DO", "DOM", "Dominican Republic"),
    ("EC", "ECU", "Ecuador"),
    ("EG", "EGY", "Egypt"),
    ("SV", "SLV", "El Salvador"),
    ("GQ", "GNQ", "Equatorial Guinea"),
    ("ER", "ERI", "Eritrea"),
    ("EE", "EST", "Estonia"),
    ("SZ", "SWZ", "Eswatini"),
    ("ET", "ETH", "Ethiopia"),
    ("FK", "FLK", "Falkland Islands"),
    ("FO", "FRO", "Faroe Islands"),
    ("FJ", "FJI", "Fiji"),
    ("FI", "FIN", "Finland"),
    ("FR", "FRA", "France"),
    ("GF", "GUF", "French Guiana"),
    ("PF", "PYF", "French Polynesia"),
    ("TF", "ATF", "French Southern Territories"),
    ("GA", "GAB", "Gabon"),
    ("GM", "GMB", "Gambia"),
    ("GE", "GEO", "Georgia"),
    ("DE", "DEU", "Germany"),
    ("GH", "GHA", "Ghana"),
    ("GI", "GIB", "Gibraltar"),
    ("GR", "GRC", "Greece"),
    ("GL", "GRL", "Greenland"),
    ("GD", "GRD", "Grenada"),
    ("GP", "GLP", "Guadeloupe"),
    ("GU", "GUM", "Guam"),
    ("GT", "GTM", "Guatemala"),
    ("GG", "GGY", "Guernsey"),
    ("GN", "GIN", "Guinea"),
    ("GW", "GNB", "Guinea-Bissau"),
    ("GY", "GUY", "Guyana"),
    ("HT", "HTI", "Haiti"),
    ("HM", "HMD", "Heard Island and McDonald Islands"),
    ("VA", "VAT", "Vatican City"),
    ("HN", "HND", "Honduras"),
    ("HK", "HKG", "Hong Kong"),
    ("HU", "HUN", "Hungary"),
    ("IS", "ISL", "Iceland"),
    ("IN", "IND", "India"),
    ("ID", "IDN", "Indonesia"),
    ("IR", "IRN", "Iran"),
    ("IQ", "IRQ", "Iraq"),
    ("IE", "IRL", "Ireland"),
    ("IM", "IMN", "Isle of Man"),
    ("IL", "ISR", "Israel"),
    ("IT", "ITA", "Italy"),
    ("JM", "JAM", "Jamaica"),
    ("JP", "JPN", "Japan"),
    ("JE", "JEY", "Jersey"),
    ("JO", "JOR", "Jordan"),
    ("KZ", "KAZ", "Kazakhstan"),
    ("KE", "KEN", "Kenya"),
    ("KI", "KIR", "Kiribati"),
    ("KP", "PRK", "North Korea"),
    ("KR", "KOR", "South Korea"),
    ("KW", "KWT", "Kuwait"),
    ("KG", "KGZ", "Kyrgyzstan"),
    ("LA", "LAO", "Laos"),
    ("LV", "LVA", "Latvia"),
    ("LB", "LBN", "Lebanon"),
    ("LS", "LSO", "Lesotho"),
    ("LR", "LBR", "Liberia"),
    ("LY", "LBY", "Libya"),
    ("LI", "LIE", "Liechtenstein"),
    ("LT", "LTU", "Lithuania"),
    ("LU", "LUX", "Luxembourg"),
    ("MO", "MAC", "Macao"),
    ("MG", "MDG", "Madagascar"),
    ("MW", "MWI", "Malawi"),
    ("MY", "MYS", "Malaysia"),
    ("MV", "MDV", "Maldives"),
    ("ML", "MLI", "Mali"),
    ("MT", "MLT", "Malta"),
    ("MH", "MHL", "Marshall Islands"),
    ("MQ", "MTQ", "Martinique"),
    ("MR", "MRT", "Mauritania"),
    ("MU", "MUS", "Mauritius"),
    ("YT", "MYT", "Mayotte"),
    ("MX", "MEX", "Mexico"),
    ("FM", "FSM", "Micronesia"),
    ("MD", "MDA", "Moldova"),
    ("MC", "MCO", "Monaco"),
    ("MN", "MNG", "Mongolia"),
    ("ME", "MNE", "Montenegro"),
    ("MS", "MSR", "Montserrat"),
    ("MA", "MAR", "Morocco"),
    ("MZ", "MOZ", "Mozambique"),
    ("MM", "MMR", "Myanmar"),
    ("NA", "NAM", "Namibia"),
    ("NR", "NRU", "Nauru"),
    ("NP", "NPL", "Nepal"),
    ("NL", "NLD", "Netherlands"),
    ("NC", "NCL", "New Caledonia"),
    ("NZ", "NZL", "New Zealand"),
    ("NI", "NIC", "Nicaragua"),
    ("NE", "NER", "Niger"),
    ("NG", "NGA", "Nigeria"),
    ("NU", "NIU", "Niue"),
    ("NF", "NFK", "Norfolk Island"),
    ("MK", "MKD", "North Macedonia"),
    ("MP", "MNP", "Northern Mariana Islands"),
    ("NO", "NOR", "Norway"),
    ("OM", "OMN", "Oman"),
    ("PK", "PAK", "Pakistan"),
    ("PW", "PLW", "Palau"),
    ("PS", "PSE", "Palestine"),
    ("PA", "PAN", "Panama"),
    ("PG", "PNG", "Papua New Guinea"),
    ("PY", "PRY", "Paraguay"),
    ("PE", "PER", "Peru"),
    ("PH", "PHL", "Philippines"),
    ("PN", "PCN", "Pitcairn"),
    ("PL", "POL", "Poland"),
    ("PT", "PRT", "Portugal"),
    ("PR", "PRI", "Puerto Rico"),
    ("QA", "QAT", "Qatar"),
    ("RE", "REU", "Réunion"),
    ("RO", "ROU", "Romania"),
    ("RU", "RUS", "Russia"),
    ("RW", "RWA", "Rwanda"),
    ("BL", "BLM", "Saint Barthélemy"),
    ("SH", "SHN", "Saint Helena"),
    ("KN", "KNA", "Saint Kitts and Nevis"),
    ("LC", "LCA", "Saint Lucia"),
    ("MF", "MAF", "Saint Martin"),
    ("PM", "SPM", "Saint Pierre and Miquelon"),
    ("VC", "VCT", "Saint Vincent and the Grenadines"),
    ("WS", "WSM", "Samoa"),
    ("SM", "SMR", "San Marino"),
    ("ST", "STP", "Sao Tome and Principe"),
    ("SA", "SAU", "Saudi Arabia"),
    ("SN", "SEN", "Senegal"),
    ("RS", "SRB", "Serbia"),
    ("SC", "SYC", "Seychelles"),
    ("SL", "SLE", "Sierra Leone"),
    ("SG", "SGP", "Singapore"),
    ("SX", "SXM", "Sint Maarten"),
    ("SK", "SVK", "Slovakia"),
    ("SI", "SVN", "Slovenia"),
    ("SB", "SLB", "Solomon Islands"),
    ("SO", "SOM", "Somalia"),
    ("ZA", "ZAF", "South Africa"),
    ("GS", "SGS", "South Georgia and the South Sandwich Islands"),
    ("SS", "SSD", "South Sudan"),
    ("ES", "ESP", "Spain"),
    ("LK", "LKA", "Sri Lanka"),
    ("SD", "SDN", "Sudan"),
    ("SR", "SUR", "Suriname"),
    ("SJ", "SJM", "Svalbard and Jan Mayen"),
    ("SE", "SWE", "Sweden"),
    ("CH", "CHE", "Switzerland"),
    ("SY", "SYR", "Syria"),
    ("TW", "TWN", "Taiwan"),
    ("TJ", "TJK", "Tajikistan"),
    ("TZ", "TZA", "Tanzania"),
    ("TH", "THA", "Thailand"),
    ("TL", "TLS", "Timor-Leste"),
    ("TG", "TGO", "Togo"),
    ("TK", "TKL", "Tokelau"),
    ("TO", "TON", "Tonga"),
    ("TT", "TTO", "Trinidad and Tobago"),
    ("TN", "TUN", "Tunisia"),
    ("TR", "TUR", "Turkey"),
    ("TM", "TKM", "Turkmenistan"),
    ("TC", "TCA", "Turks and Caicos Islands"),
    ("TV", "TUV", "Tuvalu"),
    ("UG", "UGA", "Uganda"),
    ("UA", "UKR", "Ukraine"),
    ("AE", "ARE", "United Arab Emirates"),
    ("GB", "GBR", "United Kingdom"),
    ("US", "USA", "United States"),
    ("UM", "UMI", "United States Minor Outlying Islands"),
    ("UY", "URY", "Uruguay"),
    ("UZ", "UZB", "Uzbekistan"),
    ("VU", "VUT", "Vanuatu"),
    ("VE", "VEN", "Venezuela"),
    ("VN", "VNM", "Vietnam"),
    ("VG", "VGB", "Virgin Islands (British)"),
    ("VI", "VIR", "Virgin Islands (U.S.)"),
    ("WF", "WLF", "Wallis and Futuna"),
    ("EH", "ESH", "Western Sahara"),
    ("YE", "YEM", "Yemen"),
    ("ZM", "ZMB", "Zambia"),
    ("ZW", "ZWE", "Zimbabwe"),
)

# Common non-ISO codes people type by hand (not official alpha-2/3).
_ALIASES: dict[str, str] = {
    "UK": "United Kingdom",
    "UAE": "United Arab Emirates",
    "EU": "European Union",
}

# Upper-cased code -> canonical name (both alpha-2 and alpha-3), plus aliases.
_CODE_TO_NAME: dict[str, str] = {}
for _a2, _a3, _name in _ISO_3166:
    _CODE_TO_NAME[_a2] = _name
    _CODE_TO_NAME[_a3] = _name
_CODE_TO_NAME.update(_ALIASES)

# Public: alpha-2 -> name, for callers that want the raw map.
ISO_COUNTRIES: dict[str, str] = {a2: name for a2, _a3, name in _ISO_3166}


def normalize_country(value: str | None) -> str:
    """Expand a 2/3-letter country code to its full English name.

    Values that aren't a recognized code (full names, multi-country strings,
    blanks) are returned trimmed and unchanged.
    """
    s = str(value or "").strip()
    if len(s) in (2, 3) and s.isalpha():
        name = _CODE_TO_NAME.get(s.upper())
        if name:
            return name
    return s


def looks_like_country_code(value: str | None) -> bool:
    """True when ``value`` is a recognized country code (so it will be expanded)."""
    s = str(value or "").strip()
    return bool(s) and normalize_country(s) != s
